#-- Global
language: en-US
name: Jekyll cart
title: Jekyll cart
description: Simple cart for Jekyll
timezone: America/New_York
permalink: /:year/:month/:title/

#-- Styles
highlighter: pygments

#-- Local configuration
detach:  false
port:    4000
host:    127.0.0.1
